version: '4.2'

volumes:
  postgres-db:
    driver: local
networks:
  app:
    driver: bridge

services:
  postgres_app:
    image: docker.uclv.cu/postgres:latest
    container_name: postgres_app
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./candidate_api/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - app

  backend:
    image: candidate-api:0.0.1
    container_name: candidate_api
    build:
      context: candidate_api
      dockerfile: Dockerfile
    ports:
      - 9001:8001
    tty: true
    restart: always
    working_dir: "/usr/src/app"
    env_file:
      - ./candidate_api/.env
    volumes:
      - ./candidate_api/venv:/usr/local/lib/python3.9/site-packages/app
      - ./candidate_api:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8001
    networks:
      - app
    depends_on:
      - postgres_app
  frontend:
    build:
      context: candidate_web
      target: 'develop-stage'
    image: candidate_web:0.0.1
    container_name: candidate_web
    ports:
      - '8050:8080'
    volumes:
      - './candidate_web:/app'
    command: /bin/sh -c "npm i && quasar dev"
    depends_on:
      - backend
    networks:
      - app
